### ISSUE TITLE
Tomcat Version nit Matching Latest Recommended Release?

### ISSUE THREAD

**Issue by M1kep** [jamf/jamfpro#9]
**Describe the bug**
As per https://www.jamf.com/jamf-nation/articles/380/apache-tomcat-versions-installed-by-the-jamf-pro-installer Tomcat 8.5.57 is intended for JAMF Pro 10.24.2.

**Expected behavior**
I'm not sure if it is within the scope of this project to try and keep the versions up to date, but I'm just looking to understand if this image is "safe" to use with the latest versions, or should this repo/image be used as a reference for creating an up to date version?

**Comment by battlecow** [comment]
Thanks for filing the issue!
It is outside of the scope of this project to maintain the most recent Tomcat versions as this can be used for many versions of JamfPro.  While it should be entirely possible to run an older version of Tomcat with the latest JamfPro release we always recommend running later versions of Tomcat due to older versions typically having open CVEs.  I updated the README with a link to the link you posted to assist in the versioning guidance.  I have also published a new version with the latest Tomcat.
